### PR TITLE
Supress context deadline exceeded in some cases

### PR DESCRIPTION
**Pull request by dperny**
If the context in WaitForConverge times out, it can cause API calls that
also use that context to time out, which causes them to return a context
deadline exceeded error. However, very rarely is this error the root
cause of a test failure. This change suppresses the context error if the
previous poll generated a different error; this previous error is more
likely the root cause of test failure than the context error.

Signed-off-by: Drew Erny <drew.erny@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
It seems root cause of failure is not very clear, I suggest concatenating the errors.

**Comment by dperny** [comment]
What do you mean? Concatenating if it's ambiguous, or concatenating all errors so far?

**Comment by dongluochen** [comment]
> Concatenating if it's ambiguous

**Comment by dperny** [comment]
@dongluochen pushed a new change. Instead of just hard-supressing, we wrap the error. It is almost never the case that the root cause of the problem is context deadline being exceeded when there hasn't already been an error. Concatenating is going to provide too much information.

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
