### PR TITLE
Give the system more time to converge

### PR DESCRIPTION
**Pull request by dhiltgen**
In my test environment, this takes more than 1 second to converge.

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM

**Comment by dongluochen** [comment]
I'm tracking an issue that networking requires ~10 to converge on **local** node. 
https://github.com/docker/docker/issues/30321#issuecomment-283823137

**Comment by dhiltgen** [comment]
@dperny do you think this is the right approach, or should we tune something else to make sure this passes on slower environments?

**Comment by dhiltgen** [comment]
I'd like to get this merged soon if possible, so the official image is runnable on some downstream projects which currently fail due to this timing out.

**Comment by dperny** [comment]
Hey @dhiltgen,

Sorry it took so long to get back to you on this. I missed it.

I think this is the wrong approach. The second parameter of `WaitForConverge` is the polling period, not the . You can adjust the maximum time limit by changing the timeout on the context that makes up the first parameter, which is defined above the goroutine on line 74. Try altering the timeout for that context. When I get back to working on this full-time, I'll update the documentation to better explain how this all works.

If it's still timing out, the whole test has a context defined at the top that lasts 1 minute, which is the parent context of the convergence context, and which will cancel the whole test if the it times out.

If none of what I just said makes sense, let me know; I haven't looked at this in a while and may be mistaken.

**Comment by dperny** [comment]
LGTM

**Pull request merged**
