### PR TITLE
Make AWS security group configurable

### PR DESCRIPTION
**Pull request by dhiltgen**
This should help run AWS instances in different regions or different accounts

### CODE REVIEW

**Comment by aluzzardi** [comment]
@dhiltgen Already done that in #87: "Allow configuring the security group": https://github.com/docker/docker-e2e/pull/87/commits/9feee307ddba396baaf67690c062d0185df6e0c7#diff-2558e50eda0ed93f754620591d2bc5abR75

If it's an immediate blocker, we can merge this and I'll just rebase on top.

**Comment by dhiltgen** [comment]
> If it's an immediate blocker, we can merge this and I'll just rebase on top.

I'm trying to see if I can get one of the downstream projects switched over.  With this change it looks like I can run the tests manually.  The current CI system relies on the built-in ssh key generation of `docker-machine` so I'll have to explore if its faster to injects certs into jenkins, or add the key generation to the driver...

**Comment by dhiltgen** [comment]
Just added a small update to this so it can create the cert dir on the fly.  I think this should be sufficient to get the downstream CI running, but I'll test with a hand vendoring of this PR...

**Comment by dhiltgen** [comment]
@aluzzardi can we merge this one?  My downstream merge depends on it.

**Pull request merged**
