### PR TITLE
testkit: Vendoring

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
IIRC, vendor search directories from leave to root. Why not have a `vendor` under project root directory?

**Comment by aluzzardi** [comment]
testkit could be its very own repo actually (and may be at some point?)

tests are independent

**Comment by dongluochen** [comment]
LGTM

**Comment by vdemeester** [comment]
I'm 👍 on vendoring, I really wish we wouldn't use `glide` because that tool doesn't like me at all (I tend to use `vndr` everywhere), but I'll go with the flow 😉

**Pull request closed without merging**
